FROM centos:8

ARG BAZEL_VERSION=1.1.0

RUN dnf -y upgrade --refresh && \
    dnf -y install dnf-plugins-core https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm && \
    dnf -y config-manager --set-enabled PowerTools && \
    dnf -y install git make libtool patch libatomic which \
                   autoconf automake libtool cmake python2 \
                   clang lld libstdc++-static ninja-build && \
    dnf -y clean all

RUN curl -o /usr/local/bin/bazel -Ls https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-linux-x86_64 && \
    chmod +x /usr/local/bin/bazel

ENV CC=clang CXX=clang++ USER=user HOME=/home/user
RUN mkdir -p /home/user && chmod 777 /home/user

WORKDIR /work

RUN ln -s /usr/bin/python2 /usr/bin/python

# Run without network:
# cd into prox dir
# docker run  --network=none --rm -it -v $(pwd):/work -u $(id -u):$(id -g) jwendell/proxy-build:centos8-istio1.4

# Within it, build proxy:
# bazel build //src/envoy:envoy
